version: '3'
services:
  http:
    container_name: maxwarden
    image: maxwarden
    ports:
      - 9090:80
    environment:
      - DOMAIN=https://example.net
      - HOST=0.0.0.0
      - PORT=80
      - IDENTITY_PRIVATE_KEY=lol
      - IDENTITY_DEFAULT_PASSWORD=test
      - SESSION_PRIVATE_KEY=lol
      - SMTP_SERVER=
      - SMTP_PORT=
      - SMTP_USERNAME=
      - SMTP_DISPLAY_FROM=
      - SMTP_PASSWORD=
      - SMTP_REQUIRE_AUTH=
    #volumes:
    #  - ./data:/data
    restart: always

